version: '3.8'

services:
  python:
    build: .
    container_name: python_container
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: tail -f /dev/null  # コンテナを起動後に待機状態にする
