version: '3.8'

services:
  python:
    image: python:3.8-slim
    container_name: python_container
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "
      pip install --no-cache-dir -r reqirements.txt &&
      tail -f /dev/null
      "